### ISSUE TITLE
Screenshot(s)

### ISSUE THREAD

**Issue by jasonszhao** [leeroybrun/node-terminal-status#1]
It would be nice to have a few screenshots and better explanation of what this program does. Seems promising!

**Comment by leeroybrun** [comment]
Great idea!

This is very simple, it just let you update a "status" (text) in the terminal, with 3 levels of informations : title, action, subaction.

For example, you can have multiple tasks to perform, and you can update the informations on the screen, this way the user know what is going on exactly.

I've updated the README with two new examples and gifs to show what it does.

Let me know if you need more informations.
